FROM python:3.11-slim as development

# Set environment variables
ENV PYTHON_VERSION=3.11 \
  APP_PATH=/home/python/app \
  POETRY_VIRTUALENVS_CREATE=false \
  PYTHONUNBUFFERED=1 \
  PYTHONDONTWRITEBYTECODE=1 \
  PATH=/home/python/.local/bin:/usr/local/bin:/home/python:/home/python/app/bin:$PATH

# Update package index and install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libssl-dev \
        libffi-dev \
        libpq-dev \
        curl \
        gcc \
        && \
    pip install --upgrade pip && \
    pip install --no-cache-dir poetry==1.8.3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configure user, groups and working directory for application
RUN adduser --uid 1000 --disabled-password --gecos '' python && \
  mkdir -p /home/python/app

# Set workdir
WORKDIR /home/python/app

# Copy project file and pre-install
COPY README.md .
COPY pyproject.toml .
RUN poetry lock && poetry install

# Expose ports
EXPOSE 5000

# Declare volumes
VOLUME [ "/home/python/app" ]

# Run the app
CMD ["bash"]
